In [284]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
def H_QR(A):
    m,n = A.shape
    R = A.copy()
    Q = mat(eye(m))
    p = min(m,n)
    for k in range(p):
        r = norm(R[k:,k])
        u = mat(zeros([m-k,1]))
        u[0,0] = r
        u = u + R[k:,k]
        u = u/norm(u)
        for i in range(k,n):
            R[k:,i] = 2*u*(u.T*R[k:,i])-R[k:,i]
        if m>p:
            for i in range(m):
                Q[k:,i] = 2*u*(u.T*Q[k:,i])-Q[k:,i]
        else:
            for i in range(p):
                Q[k:,i] = 2*u*(u.T*Q[k:,i])-Q[k:,i]
    return Q.T, R

In [287]:
A = mat(randn(5,5))
print(A)

[[-0.41829384 -0.65307481 -0.63825696  0.93567054  0.06696784]
 [-1.04068114 -2.35771223 -0.38927644  0.13967172  1.03771533]
 [-0.47712194  0.18952316  0.26719874  0.37832618  0.64374321]
 [ 1.52546843 -0.13651456 -0.26966791  0.60802513 -0.43921089]
 [ 0.16760204 -0.54394945 -1.3038913  -0.17942787  0.90293335]]


In [288]:
Q,R = H_QR(A)

In [13]:
Q*R

matrix([[ 0.14917169, -0.9462742 , -0.21797252, -0.42178334,  1.03905385],
        [-0.96870441, -0.72453293, -1.04357932, -1.5090027 ,  0.13484027],
        [-0.25501447,  1.96791999,  0.80889718,  1.57542791,  0.50140057],
        [-0.75828452,  0.34845107, -0.54136749,  1.00422456,  1.22589864],
        [-1.19157498, -1.71143529, -0.51335693,  0.96467422,  0.50957471]])

In [14]:
Q.T*Q

matrix([[ 1.00000000e+00,  2.12149169e-16, -8.03418046e-17,
         -7.82568282e-17, -5.13165347e-16],
        [ 2.12149169e-16,  1.00000000e+00,  3.48783403e-16,
          1.93868727e-16, -8.47094087e-18],
        [-8.03418046e-17,  3.48783403e-16,  1.00000000e+00,
         -1.15416517e-17, -1.11376824e-16],
        [-7.82568282e-17,  1.93868727e-16, -1.15416517e-17,
          1.00000000e+00, -8.72352612e-18],
        [-5.13165347e-16, -8.47094087e-18, -1.11376824e-16,
         -8.72352612e-18,  1.00000000e+00]])

In [20]:
R

matrix([[ 1.73796409e+00,  1.05521816e+00,  1.03243672e+00,
         -5.25826218e-01, -9.43784625e-01],
        [ 2.22044605e-16,  2.68887252e+00,  8.01341593e-01,
          1.43055049e+00,  1.69866878e-01],
        [ 5.55111512e-17, -2.22044605e-16,  7.99640313e-01,
          1.62411314e+00, -6.07761559e-02],
        [ 2.22044605e-16, -5.55111512e-17,  0.00000000e+00,
          1.38394917e+00,  8.88962662e-01],
        [ 2.22044605e-16,  2.22044605e-16,  0.00000000e+00,
          2.22044605e-16,  1.18244606e+00]])

In [23]:
Q

matrix([[ 0.08583129, -0.38560583,  0.00301898,  0.12289068,  0.91040095],
        [-0.55737884, -0.0507189 , -0.53458758, -0.62234977,  0.11684734],
        [-0.14673172,  0.78945876,  0.40988711, -0.21445234,  0.37580236],
        [-0.43630621,  0.30081356, -0.41514084,  0.73608919,  0.07056121],
        [-0.68561542, -0.36742591,  0.611439  ,  0.09880049, -0.10635084]])

In [148]:
def H_QR(A):
    m,n = A.shape
    R = A.copy()
    Q = mat(eye(m))
    p = min(m,n)
    for k in range(p):
        r = norm(R[k:,k])
        u = mat(zeros([m-k,1]))
        u[0,0] = r
        u = u + R[k:,k]
        u = u/norm(u)
        for i in range(k,n):
            R[k:,i] = 2*u*(u.T*R[k:,i])-R[k:,i]
        if m>p:
            for i in range(m):
                Q[k:,i] = 2*u*(u.T*Q[k:,i])-Q[k:,i]
        else:
            for i in range(p):
                Q[k:,i] = 2*u*(u.T*Q[k:,i])-Q[k:,i]
    return Q.T, R

In [149]:
def H_QR1(A):
    m,n = A.shape
    Q = mat(eye(m))
    for k in range(m):
        u = mat(zeros([m-k,1]))
        u[0,0] = norm(A[k:,k])
        u = u + A[k:,k]
        u = u/norm(u)
        for i in range(k,m):
            A[k:,i] = 2*u*(u.T*A[k:,i])-A[k:,i]
        for i in range(m):
            Q[k:,i] = 2*u*(u.T*Q[k:,i])-Q[k:,i]
    return Q.T, A

In [260]:
A = mat(randn(5,5))

In [261]:
A

matrix([[-1.10682555, -0.85152741, -1.45062666, -0.13426433,  0.25800645],
        [ 0.43398428, -0.9635351 , -1.06489944, -0.6224226 , -1.52159407],
        [-1.33925089, -0.96620176, -0.23949807,  1.39035945,  0.66373141],
        [ 0.23240613, -0.0022443 , -0.07588255,  0.23992394,  0.11117524],
        [ 1.39515965, -1.13152096,  0.20084736, -0.58834342, -0.52030061]])

In [161]:
A[:,0]

matrix([[-0.97242844],
        [-1.447484  ],
        [-0.22448812],
        [-0.31736774],
        [-0.96136328]])

In [162]:
Q,R = H_QR(A)
Q1,R1 = H_QR1(A)

In [163]:
Q

matrix([[-0.47930431,  0.63587496, -0.22263879, -0.3770344 ,  0.41738165],
        [-0.71345644,  0.07837025,  0.05830506,  0.57528295, -0.38792791],
        [-0.11064889, -0.11869315,  0.70060632,  0.24611751,  0.64980437],
        [-0.15642871, -0.50371684, -0.64872849,  0.26447087,  0.48063075],
        [-0.47385036, -0.56718818,  0.18797508, -0.62958392, -0.14850203]])

In [164]:
Q1

matrix([[-0.47930431,  0.63587496, -0.22263879, -0.3770344 ,  0.41738165],
        [-0.71345644,  0.07837025,  0.05830506,  0.57528295, -0.38792791],
        [-0.11064889, -0.11869315,  0.70060632,  0.24611751,  0.64980437],
        [-0.15642871, -0.50371684, -0.64872849,  0.26447087,  0.48063075],
        [-0.47385036, -0.56718818,  0.18797508, -0.62958392, -0.14850203]])

In [292]:
b = mat(randn(5,1))

In [293]:
x = np.linalg.solve(A,b)

In [294]:
x

matrix([[ 0.79440886],
        [-1.23172582],
        [ 0.41234992],
        [-0.6963407 ],
        [-1.92040688]])

In [439]:
def H_QR2(A,b):
    m,n = A.shape
    for k in range(m):
        u = mat(zeros([m-k,1]))
        u[0,0] = norm(A[k:,k])
        u = u + A[k:,k]
        u = u/norm(u)
        for i in range(k,m):
            A[k:,i] = 2*u*(u.T*A[k:,i])-A[k:,i]
        for i in range(m):
            b[k:,0] = 2*u*(u.T*b[k:,0])-b[k:,0]
    return b, A

In [440]:
b2,A2 = H_QR2(A,b)

In [441]:
A2

matrix([[ 1.89646232e+00,  1.35543012e+00,  1.21395984e+00,
         -5.87784186e-01, -6.37030545e-01],
        [-1.11022302e-16,  1.09664721e+00, -8.45212778e-01,
          1.14892446e+00, -2.15973242e+00],
        [ 3.46944695e-18,  0.00000000e+00,  2.62081523e+00,
          1.46551287e+00,  7.06693278e-02],
        [-2.77555756e-17,  0.00000000e+00,  0.00000000e+00,
          8.27311142e-01, -6.07292033e-01],
        [ 2.22044605e-16,  0.00000000e+00,  0.00000000e+00,
          1.11022302e-16,  5.92015743e-01]])

In [297]:
b2

matrix([[ 1.90101571],
        [-0.61551218],
        [ 1.57356123],
        [-0.38331354],
        [-1.55112537]])

In [298]:
x3 = np.linalg.solve(A2,b2)

In [299]:
x3

matrix([[ 0.79440886],
        [-1.23172582],
        [ 0.41234992],
        [-0.6963407 ],
        [-1.92040688]])

In [300]:
A2

matrix([[ 1.95978997e+00,  1.19245558e+00, -4.35248166e-02,
          9.19506720e-02, -9.86715889e-01],
        [ 0.00000000e+00,  2.21670918e+00,  9.84900368e-01,
         -4.34751969e-01, -7.32139987e-01],
        [ 0.00000000e+00,  3.37763655e-17,  1.19634169e+00,
         -4.03745703e-02, -5.47871067e-01],
        [ 0.00000000e+00, -3.81233227e-16,  2.77555756e-17,
          1.11396268e+00, -2.04323375e-01],
        [ 0.00000000e+00, -1.68881828e-17,  1.73472348e-18,
          4.16333634e-17,  8.07706630e-01]])

In [196]:
x4 = mat(zeros([5,1]))

In [201]:
x4

matrix([[ 0.        ],
        [ 0.        ],
        [ 0.08400807],
        [ 0.85160949],
        [-0.87873684]])

In [198]:
x4[-1,0] = b2[-1,0]/A2[-1,-1]

In [199]:
x4[-2,0] = (b2[-2,0]-A2[-2,-1]*x4[-1,0])/A2[-2,-2]

In [200]:
x4[-3,0] = (b2[-3,0]-A2[-3,-1]*x4[-1,0]-A2[-3,-2]*x4[-2,0])/A2[-3,-3]

In [227]:
x5 = mat(zeros([5,1]))
for i in range(1,6):
    x5[-i,0] = b2[-i,0]
    for j in range(1,i):
        x5[-i,0] = x5[-i,0]-A2[-i,-j]*x5[-j,0]
    x5[-i,0] = x5[-i,0]/A2[-i,-i]

In [228]:
x5

matrix([[-0.67901289],
        [ 0.82889155],
        [ 0.08400807],
        [ 0.85160949],
        [-0.87873684]])

In [229]:
A2*x5

matrix([[ 0.60414669],
        [-0.26362636],
        [-0.73834819],
        [ 0.69394769],
        [-1.36026063]])

In [230]:
b2

matrix([[ 0.60414669],
        [-0.26362636],
        [-0.73834819],
        [ 0.69394769],
        [-1.36026063]])

In [306]:
x = H_QR2(A,b)

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


In [235]:
A*x

matrix([[ 0.60414669],
        [-0.26362636],
        [-0.73834819],
        [ 0.69394769],
        [-1.36026063]])

In [236]:
b

matrix([[ 0.60414669],
        [-0.26362636],
        [-0.73834819],
        [ 0.69394769],
        [-1.36026063]])

In [237]:
x

matrix([[-0.67901289],
        [ 0.82889155],
        [ 0.08400807],
        [ 0.85160949],
        [-0.87873684]])

In [453]:
def H_QR2(A,b):
    m,n = A.shape
    u = mat(zeros([m,1]))
    for k in range(m):
        for i in range(m):
            u[i,0] = 0
        u[k,0] = norm(A[k:,k])
        u[k:,0] = u[k:,0] + A[k:,k]
        u = u/norm(u)
        for i in range(k,m):
            A[k:,i] = 2*u[k:,0]*(u[k:,0].T*A[k:,i])-A[k:,i]
        for i in range(m):
            b[k:,0] = 2*u[k:,0]*(u[k:,0].T*b[k:,0])-b[k:,0]
    return b, A

In [443]:
m=5
k=3
u = mat(zeros([m,1]))
for i in range(m):
    u[i,0] = 0
u[k,0] = norm(A[k:,k])
for i in range(k,m):
    u[i,0] = u[i,0] + A[i,k]
u = u/norm(u)

In [462]:
A = mat(randn(5,5))
b = mat(randn(5,1))

In [463]:
b5,A5 = H_QR2(A,b)

In [464]:
x5 = np.linalg.solve(A5,b5)

In [465]:
x5

matrix([[ 1.24951991],
        [ 1.32985832],
        [ 0.76960198],
        [-0.33386965],
        [ 2.7553814 ]])

In [466]:
A5

matrix([[ 2.79617481e+00, -5.86442390e-01, -2.87746258e+00,
         -1.58649003e-02,  2.59680567e-01],
        [-6.93889390e-18,  1.28414888e+00, -1.04407124e+00,
         -9.44386945e-01, -5.51657785e-01],
        [-5.55111512e-17, -3.33066907e-16,  1.28317581e+00,
          3.70398479e-01, -1.03894848e+00],
        [-1.11022302e-16,  2.77555756e-16,  0.00000000e+00,
          8.26228590e-01,  3.57007167e-03],
        [-4.44089210e-16,  5.55111512e-17,  0.00000000e+00,
         -2.22044605e-16,  4.79578133e-01]])

In [467]:
def prefect_H_QR(A,b):
    m,n = A.shape
    u = mat(zeros([m,1]))
    for k in range(m):
        for i in range(m):
            u[i,0] = 0
        u[k,0] = norm(A[k:,k])
        for i in range(k,m):
            u[i,0] = u[i,0] + A[i,k]
        u = u/norm(u)
        for i in range(k,m):
            A[k:,i] = 2*u[k:,0]*(u[k:,0].T*A[k:,i])-A[k:,i]
        for i in range(m):
            b[k:,0] = 2*u[k:m,0]*(u[k:m,0].T*b[k:,0])-b[k:,0]
    x = mat(zeros([m,1]))
    for i in range(1,m+1):
        x[-i,0] = b[-i,0]
        for j in range(1,i):
            x[-i,0] = x[-i,0]-A[-i,-j]*x[-j,0]
        x[-i,0] = x[-i,0]/A[-i,-i]  
    return x

In [468]:
A = mat(randn(100,100)*5)
b = mat(randn(100,1)*3)

In [469]:
x = prefect_H_QR(A,b)

In [470]:
y = A*x

In [471]:
y

matrix([[ 3.36374606],
        [-0.16363751],
        [ 1.54637986],
        [-1.73115965],
        [-0.68651102],
        [ 1.13661408],
        [ 4.8096067 ],
        [-1.84325869],
        [-2.8561249 ],
        [ 1.74957719],
        [ 2.53275957],
        [-3.7596278 ],
        [-0.35798403],
        [-3.51034166],
        [ 1.68610382],
        [-0.75468628],
        [-1.20944043],
        [-0.94617598],
        [-2.99773456],
        [ 7.0515075 ],
        [ 3.61734309],
        [ 1.19741437],
        [-1.66460582],
        [-1.51812424],
        [-3.09904383],
        [ 5.50643479],
        [ 3.5741598 ],
        [ 2.52682666],
        [ 1.39474452],
        [-1.06380481],
        [ 0.13835469],
        [-1.32225983],
        [-3.78681675],
        [-2.92239022],
        [-1.02856439],
        [ 0.41704798],
        [-0.45481734],
        [ 5.17634928],
        [ 2.89101536],
        [-5.25547586],
        [ 2.94567026],
        [-0.25617989],
        [-0.51910187],
        [ 2

In [472]:
b

matrix([[ 3.36374606],
        [-0.16363751],
        [ 1.54637986],
        [-1.73115965],
        [-0.68651102],
        [ 1.13661408],
        [ 4.8096067 ],
        [-1.84325869],
        [-2.8561249 ],
        [ 1.74957719],
        [ 2.53275957],
        [-3.7596278 ],
        [-0.35798403],
        [-3.51034166],
        [ 1.68610382],
        [-0.75468628],
        [-1.20944043],
        [-0.94617598],
        [-2.99773456],
        [ 7.0515075 ],
        [ 3.61734309],
        [ 1.19741437],
        [-1.66460582],
        [-1.51812424],
        [-3.09904383],
        [ 5.50643479],
        [ 3.5741598 ],
        [ 2.52682666],
        [ 1.39474452],
        [-1.06380481],
        [ 0.13835469],
        [-1.32225983],
        [-3.78681675],
        [-2.92239022],
        [-1.02856439],
        [ 0.41704798],
        [-0.45481734],
        [ 5.17634928],
        [ 2.89101536],
        [-5.25547586],
        [ 2.94567026],
        [-0.25617989],
        [-0.51910187],
        [ 2

In [475]:
y[57,0]-b[57,0]

-2.6645352591003757e-15