In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
from scipy.linalg import lu

In [37]:
def forward(L, b):
    n = L.shape[0]
    y = mat(zeros([n,1]))
    y[0] = float(b[0])/float(L[0,0])
    for i in range(len(b)):
        tmp = float(b[i])
        for j in range(i):
            tmp -= float(L[i,j]*y[j])
        y[i] = tmp/float(L[i,i])
    return y

In [119]:
L = mat(([1,0,0],[2,1,0],[4,5,1]))
y = mat(([4],[5],[6]))
b = L*y

In [120]:
forward(L,b)

matrix([[4.],
        [5.],
        [6.]])

In [227]:
def backward(U, b):
    n = U.shape[0]
    y = mat(zeros([n,1]))
    y[n-1] = float(b[n-1])/float(U[n-1,n-1])
    for i in range(len(b)-1,-1,-1):
        tmp = float(b[i])
        for j in range(len(b)-1,i,-1):
            tmp -= float(U[i,j]*y[j])
        y[i] = tmp/float(U[i,i])
    return y

In [228]:
U = mat(([1,2,3],[0,4,5],[0,0,6]))
y = mat(([7],[8],[9]))
b = U*y

In [229]:
backward(U, b)

matrix([[7.],
        [8.],
        [9.]])

In [230]:
U1 = mat(([2,3,4,5],[0,1,2,3],[0,0,4,5],[0,0,0,6]))
y1 = mat(([6],[7],[8],[9]))
b1 = U1*y1

In [231]:
backward(U1, b1)

matrix([[6.],
        [7.],
        [8.],
        [9.]])

In [232]:
def backward2(U, b):
    n = U.shape[0]
    y = mat(zeros([n,1]))
    y[n-1] = float(b[n-1])/float(U[n-1,n-1])
    for i in range(1,len(b)+1):
        tmp = float(b[-i])
        for j in range(i):
            tmp -= float(U[-i,-j]*y[-j])
        y[-i] = tmp/float(U[-i,-i])
    return y

In [233]:
backward2(U1, b1)

matrix([[6.],
        [7.],
        [8.],
        [9.]])

In [251]:
A = mat(10*rand(4,4))
b = mat(10*rand(4,1))
P,L,U = lu(A)
P = mat(P)
L = mat(L)
U = mat(U)

In [252]:
b0 = forward(L, b)
b0

matrix([[1.65260986],
        [1.88883496],
        [3.86468089],
        [0.92176451]])

In [253]:
x = backward2(U, b0)
x

matrix([[-0.47145026],
        [-0.90969739],
        [ 1.08333391],
        [ 0.24107597]])

In [254]:
x0 = backward2(U, b0)
x0

matrix([[-0.47145026],
        [-0.90969739],
        [ 1.08333391],
        [ 0.24107597]])

In [255]:
A*x

matrix([[2.06425286],
        [1.65260986],
        [0.0048547 ],
        [4.80882474]])

In [256]:
A*x0

matrix([[2.06425286],
        [1.65260986],
        [0.0048547 ],
        [4.80882474]])

In [257]:
P*b

matrix([[2.06425286],
        [1.65260986],
        [0.0048547 ],
        [4.80882474]])

In [258]:
def solve(L,U,b):
    y = forward(L,b)
    return backward(U,y)

In [259]:
solve(L,U,b)

matrix([[-0.47145026],
        [-0.90969739],
        [ 1.08333391],
        [ 0.24107597]])