In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
p = 6

In [6]:
A = mat(randn(p, p))
A = A*A.T
A

matrix([[ 7.08608724, -6.08876257, -0.67700853,  1.23222858, -0.86729814,
          0.08606823],
        [-6.08876257, 12.26732849, -1.47926868, -1.69058624, -1.06826986,
         -4.36849797],
        [-0.67700853, -1.47926868,  3.02510293,  1.61072314,  2.29785842,
         -0.04589143],
        [ 1.23222858, -1.69058624,  1.61072314,  3.42204102,  1.24515239,
          0.30047091],
        [-0.86729814, -1.06826986,  2.29785842,  1.24515239,  2.42935172,
         -0.89588315],
        [ 0.08606823, -4.36849797, -0.04589143,  0.30047091, -0.89588315,
          6.149042  ]])

In [9]:
e, g = eig(A)

In [11]:
print(e)

[17.93005549  6.77166621  6.4791017   2.53272421  0.08963241  0.57577339]


In [12]:
print(g)

[[-0.46718728  0.36912686  0.56268559  0.20387899  0.38523492 -0.3726845 ]
 [ 0.81098129  0.08656175  0.06154907  0.36624613  0.33167938 -0.29475529]
 [-0.08040853 -0.61502343  0.02123727 -0.08465122 -0.2183657  -0.74831826]
 [-0.15254033 -0.40152576  0.16761218  0.81271644 -0.17501301  0.31028551]
 [-0.03629908 -0.55496195  0.10385604 -0.24957204  0.73563718  0.27652355]
 [-0.30494866  0.09377052 -0.80016604  0.30714341  0.34943905 -0.20372282]]


In [14]:
x0 = mat(randn(p , 1))
x0 = x0/norm(x0)
x1 = A*x0
x1 = x1/norm(x1)
while norm(x1-x0) > 10**-14:
    x0 = x1
    x1 = A*x0
    x1 = x1/norm(x1)
print(x1)

[[-0.46718728]
 [ 0.81098129]
 [-0.08040853]
 [-0.15254033]
 [-0.03629908]
 [-0.30494866]]


In [22]:
eval1 = float((A*x1)[0]/x1[0])
print(eval1)

17.930055486684502


In [27]:
B = inv(A)
x0 = mat(randn(p , 1))
x0 = x0/norm(x0)
x1 = B*x0
x1 = x1/norm(x1)
while norm(x1-x0) > 10**-14:
    x0 = x1
    x1 = B*x0
    x1 = x1/norm(x1)
print(x1)

[[-0.38523492]
 [-0.33167938]
 [ 0.2183657 ]
 [ 0.17501301]
 [-0.73563718]
 [-0.34943905]]


In [30]:
eval2 = float((A*x1)[0]/x1[0])
print(eval2)

0.08963241369115844


In [31]:
lamb = 5
C = inv(A-5*mat(eye(p)))
x0 = mat(randn(p , 1))
x0 = x0/norm(x0)
x1 = C*x0
x1 = x1/norm(x1)
while norm(x1-x0) > 10**-14:
    x0 = x1
    x1 = C*x0
    x1 = x1/norm(x1)
print(x1)

[[-0.56268559]
 [-0.06154907]
 [-0.02123727]
 [-0.16761218]
 [-0.10385604]
 [ 0.80016604]]


In [32]:
eval3 = float((A*x1)[0]/x1[0])
print(eval3)

6.479101696888832
