In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
A = mat(randn(4,3))
print(A)

[[-0.35449364 -0.05790339 -1.82817724]
 [ 0.04360973 -1.19004485 -0.73220357]
 [-1.68875374 -0.14648067  0.29754699]
 [-0.16793053  0.59024758  0.05859949]]


In [3]:
B =A.T*A
print(B)

[[ 3.0076574   0.11687804  0.10382176]
 [ 0.11687804  1.78940834  0.96821607]
 [ 0.10382176  0.96821607  3.97032222]]


In [4]:
e,g = eig(B)
print(e)

[ 4.35242677  2.9966724   1.41828878]


In [5]:
A[:,1] = 3*A[:,0]-2*A[:,2]
B1 = A.T*A
print(B1)

[[  3.0076574    8.81532867   0.10382176]
 [  8.81532867  41.70434431  -7.62917915]
 [  0.10382176  -7.62917915   3.97032222]]


In [6]:
e1,g1 = eig(B1)
print(e1)

[  4.49679384e+01   1.59539041e-16   3.71438555e+00]


In [7]:
A = mat(randn(4,8))
B = A.T*A
e2,g2 = eig(B)

In [8]:
print(e2)

[  0.00000000e+00   1.95959630e+00   5.21215405e+00   2.01988165e+01
   1.57161834e+01   2.71433135e-16  -6.26234813e-16  -2.63233450e-16]


In [9]:
A = mat(randn(4,3))
B = mat(randn(3,2))
C = A*B

In [10]:
print(C)

[[-1.32913135  1.08216903]
 [-0.01316984 -2.71105774]
 [-0.0595968   0.05653919]
 [ 0.056207   -1.59525036]]


In [11]:
A = mat(randn(4,3))
A[:,1] = 2*A[:,0]+3*A[:,2]
P = A*inv(A.T*A)*A.T

In [12]:
print(P)

[[ 1.23423786 -0.88337661  0.13952443  1.50266197]
 [-4.24934859  3.56628806 -0.50306039 -5.22433131]
 [ 0.22629786 -0.13519767  0.02442456  0.27292142]
 [ 2.34086516 -0.62834923  0.21935715  2.7485735 ]]


In [15]:
A1 = A[:,0:2:]
print(A)

[[-0.2716036  -4.904665   -1.45381927]
 [ 0.86011493  3.09409963  0.45795659]
 [-0.05948328 -0.53645086 -0.13916143]
 [-0.39513364 -5.93102988 -1.71358754]]


In [16]:
print(A1)

[[-0.2716036  -4.904665  ]
 [ 0.86011493  3.09409963]
 [-0.05948328 -0.53645086]
 [-0.39513364 -5.93102988]]


In [17]:
P1 = A1*inv(A1.T*A1)*A1.T
print(P1)

[[ 0.43251867  0.04906962  0.03338991  0.49185725]
 [ 0.04906962  0.99444721 -0.03896226 -0.03995083]
 [ 0.03338991 -0.03896226  0.00442581  0.04211026]
 [ 0.49185725 -0.03995083  0.04211026  0.56860831]]


In [23]:
A = mat(randn(4,6))
P = A*inv(A.T*A)*A.T
print(P)

[[ 3.55495083 -4.96075756  3.3814329   4.54890471]
 [ 1.23726674  0.3304299   0.4728539   9.53475827]
 [-1.00036305  8.83246008  3.4500959  -5.55509366]
 [ 1.82493199 -0.28887296 -3.0773847  -4.56581667]]


In [24]:
A1 = A[:,0:4]
P1 = A1*inv(A1.T*A1)*A1.T
print(P1)

[[  1.00000000e+00   2.22044605e-16  -3.33066907e-16   2.22044605e-16]
 [  8.32667268e-17   1.00000000e+00  -5.55111512e-17   1.38777878e-16]
 [  1.38777878e-16   2.77555756e-16   1.00000000e+00   0.00000000e+00]
 [  1.11022302e-16  -2.77555756e-16  -1.59594560e-16   1.00000000e+00]]
